"use strict";

module.exports = [
  {
    entity: 'grund',
    columns: ['husnummer']
  }, {
    entity: 'grund',
    columns: ['bestemtFastEjendom']
  }, {
    entity: 'bygning',
    columns: ['husnummer']
  }, {
    entity: 'bygning',
    columns: ['jordstykke']
  }, {
    entity: 'bygning',
    columns: ['ejerlejlighed']
  }, {
    entity: 'bygning',
    columns: ['grund']
  }, {
    entity: 'bygning',
    columns: ['byg021BygningensAnvendelse']
  }, {
    entity: 'opgang',
    columns: ['bygning']
  }, {
    entity: 'opgang',
    columns: ['adgangFraHusnummer']
  }, {
    entity: 'enhed',
    columns: ['adresseIdentificerer']
  }, {
    entity: 'enhed',
    columns: ['enh020EnhedensAnvendelse']
  }, {
    entity: 'enhed',
    columns: ['opgang']
  }, {
    entity: 'enhed',
    columns: ['etage']
  }, {
    entity: 'etage',
    columns: ['bygning']
  }, {
    entity: 'tekniskanlæg',
    columns: ['jordstykke']
  }, {
    entity: 'tekniskanlæg',
    columns: ['husnummer']
  }, {
    entity: 'tekniskanlæg',
    columns: ['enhed']
  }, {
    entity: 'tekniskanlæg',
    columns: ['ejerlejlighed']
  }, {
    entity: 'tekniskanlæg',
    columns: ['bygningPåFremmedGrund']
  }, {
    entity: 'tekniskanlæg',
    columns: ['bygning']
  }, {
    entity: 'tekniskanlæg',
    columns: ['grund']
  }, {
    entity: 'tekniskanlæg',
    columns: ['tek020Klassifikation']
  }, {
    entity: 'ejendomsrelation',
    columns: ['bygningPåFremmedGrund']
  }, {
    entity: 'ejendomsrelation',
    columns: ['ejendomsnummer']
  }, {
    entity: 'ejendomsrelation',
    columns: ['samletFastEjendom']
  }, {
    entity: 'ejendomsrelation',
    columns: ['bfeNummer']
  }, {
    entity: 'grundjordstykke',
    columns: ['grund']
  }, {
    entity: 'grundjordstykke',
    columns: ['jordstykke']
  }, {
    entity: 'bygningpåfremmedgrund',
    columns: ['bygning']
  }, {
    entity: 'bygningpåfremmedgrund',
    columns: ['bygningPåFremmedGrund']
  }, {
    entity: 'enhedejerlejlighed',
    columns: ['ejerlejlighed']
  }, {
    entity: 'enhedejerlejlighed',
    columns: ['enhed']
  }, {
    entity: 'fordelingsareal',
    columns: ['bygning']
  }, {
    entity: 'fordelingaffordelingsareal',
    columns: ['fordelingsareal']
  }, {
    entity: 'fordelingaffordelingsareal',
    columns: ['enhed']
  }];
