"use strict";

module.exports = {
  bygning: {
    oisTable: 'CO40100T',
    fields: [
      { name: 'OIS_AJOUR', type: 'string'},
      { name: 'ois_id', type: 'integer', oisType: 'int'},
      { name: 'ois_ts', type: 'timestamp', oisType: 'varchar', oisLength: 26 },
      { name: 'Bygning_id', dawaName: 'id', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'bygningsnr', dawaName: 'bygningsnr', type: 'integer', oisType: 'char', oisLength: 3 },
      { name: 'ObjStatus', dawaName: 'status', type: 'integer', oisType: 'tinyint' },
      { name: 'NyByg', type: 'integer', oisType: 'tinyint' },
      { name: 'Crud_id', type: 'string', oisType: 'bigint' },
      { name: 'Grund_id', dawaName: 'grundid', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'Byggesag_id', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'BygStam_id', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'AdgAdr_id', dawaName: 'adgangsadresseid', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'BYG_ANVEND_KODE', dawaName: 'anvendelseskode', type: 'integer', oisType: 'smallint' },
      { name: 'Klassifikation', type: 'integer', oisType: 'smallint' },
      { name: 'AnvKonvKilde', type: 'integer', oisType: 'smallint' },
      { name: 'AntLejMKoekken', dawaName: 'lejlighedermedkøkken', type: 'integer', oisType: 'int' },
      { name: 'AntLejUKoekken', dawaName: 'lejlighederudenkøkken', type: 'integer', oisType: 'int' },
      { name: 'OPFOERELSE_AAR', dawaName: 'opførelsesår', type: 'integer', oisType: 'smallint' },
      { name: 'OMBYG_AAR', dawaName: 'ombygningsår', type: 'integer', oisType: 'smallint' },
      { name: 'MIDL_OPRET_KODE', dawaName: 'midlertidigkode', type: 'integer', oisType: 'tinyint' },
      { name: 'UdloebDatoMidl', dawaName: 'midlertidigdato', type: 'string', oisType: 'varchar', oisLength: 26 },
      { name: 'BYG_VANDFORSY_KODE', dawaName: 'vandforsyning', type: 'integer', oisType: 'tinyint' },
      { name: 'BYG_AFLOEB_KODE', dawaName: 'afløbsforhold', type: 'integer', oisType: 'varchar', oisLength: 3 },
      { name: 'BYG_AFLOEB_TILL', type: 'integer', oisType: 'varchar', oisLength: 3 },
      { name: 'YDERVAEG_KODE', dawaName: 'ydervægsmateriale', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'TAG_KODE', dawaName: 'tagmateriale', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'SuppYderVaegMat', dawaName: 'supplerendeydervægsmateriale', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'SuppTagDaekMat', dawaName: 'supplerendetagmateriale', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'AsbestMateriale', dawaName: 'asbest', type:'integer', oisType: 'char', oisLength: 1 },
      { name: 'KILDE_MATR_KODE', dawaName: 'materialekilde', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'BYG_ARL_SAML', dawaName: 'areal', type: 'integer', oisType: 'int' },
      { name: 'BYG_BOLIG_ARL_SAML', dawaName: 'boligareal', type: 'integer', oisType: 'int' },
      { name: 'ERHV_ARL_SAML', dawaName: 'erhvervsareal', type: 'integer', oisType: 'int' },
      { name: 'BYG_BEBYG_ARL', dawaName: 'bebyggetareal', type: 'integer', oisType: 'int' },
      { name: 'GARAGE_INDB_ARL', dawaName: 'garageareal', type: 'integer', oisType: 'int' },
      { name: 'CARPORT_INDB_ARL', dawaName: 'carportareal', type: 'integer', oisType: 'int' },
      { name: 'UDHUS_INDB_ARL', dawaName: 'udhusareal', type: 'integer', oisType: 'int' },
      { name: 'UDESTUE_ARL', dawaName: 'udestueareal', type: 'integer', oisType: 'int' },
      { name: 'LukOverdaekAreal', dawaName: 'lukketoverdækningareal', type: 'integer', oisType: 'int' },
      { name: 'AFFALDSRUM_ARL', dawaName: 'affaldsrumareal', type: 'integer', oisType: 'int' },
      { name: 'ANDET_ARL', dawaName: 'andetareal',  type: 'integer', oisType: 'int' },
      { name: 'OverdaekAreal', dawaName: 'overdækningsareal', type: 'integer', oisType: 'int' },
      { name: 'AabenOverdaekAreal', dawaName: 'åbenoverdækningsareal', type: 'integer', oisType: 'int' },
      { name: 'AdgangsAreal', dawaName: 'adgangsareal', type: 'integer', oisType: 'int' },
      { name: 'Carport_Princip', dawaName: 'carportberegningsprincip', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'KILDE_ARL_KODE', dawaName: 'arealkilde', type: 'integer', oisType: 'tinyint' },
      { name: 'ETAGER_ANT', dawaName: 'etager', type: 'integer', oisType: 'smallint' },
      { name: 'ETAGER_AFVIG_KODE', dawaName: 'afvigendeetager', type: 'integer', oisType: 'tinyint' },
      { name: 'VARMEINSTAL_KODE', dawaName: 'varmeinstallation', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'OPVARMNING_KODE', dawaName: 'opvarmningsmiddel', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'VARME_SUPPL_KODE', dawaName: 'supplerendevarme', type: 'integer', oisType: 'varchar', oisLength: 2 },
      { name: 'SIKRINGSRUM_ANT', dawaName: 'sikringsrumpladser', type: 'integer', oisType: 'smallint' },
      { name: 'FREDNING_KODE', dawaName: 'fredning', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'BevarVaerdig', dawaName: 'bevaringsværdighed', type: 'integer', oisType: 'varchar', oisLength: 200 },
      { name: 'UdlejForhold1', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'HusLeje', type: 'integer', oisType: 'int' },
      { name: 'HuslejeOplysDato', type: 'string', oisType: 'varchar', oisLength: 26 },
      { name: 'SagsType', dawaName: 'sagstype', type: 'integer', oisType: 'char', oisLength: 1 },
      { name: 'BygPktNoejagtigKls', dawaName: 'byggepunktnøjagtighed', type: 'string', oisType: 'varchar', oisLength: 2 },
      { name: 'BygPkt_id', dawaName: 'byggepunktid', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'FOT_id', dawaName: 'fotid', type: 'integer', oisType: 'int' },
      { name: 'StormRaadPaalaeg', dawaName: 'oversvømmelsesselvrisiko', type: 'integer', oisType: 'tinyint' },
      { name: 'StormRaadPaalaegDato', dawaName: 'oversvømmelsesselvrisikodato', type: 'string', oisType: 'varchar', oisLength: 26 },
      { name: 'BygSkadeForsikSelskab', dawaName: 'forsikringsselskab', type: 'string', oisType: 'char', oisLength: 2 },
      { name: 'BygSkadeForsikSelskabDato', dawaName: 'forsikringsselskabdato', type: 'string', oisType: 'varchar', oisLength: 26 },
      { name: 'KomFelt1', type: 'string', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt2', type: 'string', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt3', type: 'string', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt4', type: 'string', oisType: 'int' },
      { name: 'KomFelt5', type: 'string', oisType: 'int' },
      { name: 'KomFelt6', type: 'string', oisType: 'int' },
      { name: 'JourNr', type: 'string', oisType: 'varchar', oisLength: 60 },
      { name: 'ESDH_Ref', type: 'string', oisType: 'varchar', oisLength: 200 },
      { name: 'SikKlas', type: 'integer', oisType: 'tinyint' },
      { name: 'OPRET_TS', dawaName: 'oprettet', type: 'timestamp', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', dawaName: 'ændret', type: 'timestamp', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', type: 'string', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', dawaName: 'ophørt', type: 'timestamp', oisType: 'varchar', oisLength: 26 },
      { name: 'Kommune_id', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'KomKode', dawaName: 'kommunekode', type: 'integer', oisType: 'char', oisLength: 4 },
      { name: 'eRef', type: 'uuid', oisType: 'uniqueidentifier' },
      { name: 'Landsejerlavkode', dawaName: 'ejerlavkode', type: 'integer', oisType: 'int' },
      { name: 'KomEjerlavKode', type: 'integer', oisType: 'smallint' },
      { name: 'MatrNr', dawaName: 'matrikelnr', type: 'string', oisType: 'varchar', oisLength: 10 },
      { name: 'ESREjdNr', type: 'integer', oisType: 'char', oisLength: 6 },
      { name: 'Matr_art_kode', type: 'integer', oisType: 'smallint' },
      { name: 'Delnr', type: 'string', oisType: 'varchar', oisLength: 3 },
      { name: 'Opdelingsnr', type: 'integer', oisType: 'varchar', oisLength: 3 },
      { name: 'BygSkadeOmfatFors', type: 'string', oisType: 'varchar', oisLength: 2 },
      { name: 'Gyldighedsdato', type: 'string', oisType: 'varchar', oisLength: 26 }
    ]
  }
};