"use strict";

module.exports = {
  bygning: {
    oisTable: 'CO40100T',
    fields: [
      { name: 'OIS_AJOUR', type: 'string'},
      { name: 'ois_id', type: 'integer' },
      { name: 'ois_ts', type: 'timestamp' },
      { name: 'Bygning_id', type: 'uuid' },
      { name: 'bygningsnr', type: 'integer'},
      { name: 'ObjStatus', type: 'integer'},
      { name: 'NyByg', type: 'integer'},
      { name: 'Crud_id', type: 'string'},
      { name: 'Grund_id', type: 'uuid' },
      { name: 'Byggesag_id', type: 'uuid'},
      { name: 'BygStam_id', type: 'uuid'},
      { name: 'AdgAdr_id', type: 'uuid' },
      { name: 'BYG_ANVEND_KODE', type: 'integer' },
      { name: 'Klassifikation', type: 'integer'},
      { name: 'AnvKonvKilde', type: 'integer'},
      { name: 'AntLejMKoekken', type: 'integer'},
      { name: 'AntLejUKoekken', type: 'integer'},
      { name: 'OPFOERELSE_AAR', type: 'integer' },
      { name: 'OMBYG_AAR', type: 'integer'},
      { name: 'MIDL_OPRET_KODE', type: 'integer'},
      { name: 'UdloebDatoMidl', type: 'string'},
      { name: 'BYG_VANDFORSY_KODE', type: 'integer'},
      { name: 'BYG_AFLOEB_KODE', type: 'integer'},
      { name: 'BYG_AFLOEB_TILL', type: 'integer'},
      { name: 'YDERVAEG_KODE', type: 'integer'},
      { name: 'TAG_KODE', type: 'integer'},
      { name: 'SuppYderVaegMat', type: 'integer'},
      { name: 'SuppTagDaekMat', type: 'integer'},
      { name: 'AsbestMateriale', type:'integer'},
      { name: 'KILDE_MATR_KODE', type: 'integer'},
      { name: 'BYG_ARL_SAML', type: 'integer'},
      { name: 'BYG_BOLIG_ARL_SAML', type: 'integer'},
      { name: 'ERHV_ARL_SAML', type: 'integer'},
      { name: 'BYG_BEBYG_ARL', type: 'integer'},
      { name: 'GARAGE_INDB_ARL', type: 'integer'},
      { name: 'CARPORT_INDB_ARL', type: 'integer'},
      { name: 'UDHUS_INDB_ARL', type: 'integer'},
      { name: 'UDESTUE_ARL', type: 'integer'},
      { name: 'LukOverdaekAreal', type: 'integer'},
      { name: 'AFFALDSRUM_ARL', type: 'integer'},
      { name: 'ANDET_ARL', type: 'integer'},
      { name: 'OverdaekAreal', type: 'integer'},
      { name: 'AabenOverdaekAreal', type: 'integer'},
      { name: 'AdgangsAreal', type: 'integer'},
      { name: 'Carport_Princip', type: 'integer'},
      { name: 'KILDE_ARL_KODE', type: 'integer'},
      { name: 'ETAGER_ANT', type: 'integer'},
      { name: 'ETAGER_AFVIG_KODE', type: 'integer'},
      { name: 'VARMEINSTAL_KODE', type: 'integer'},
      { name: 'OPVARMNING_KODE', type: 'integer'},
      { name: 'VARME_SUPPL_KODE', type: 'integer'},
      { name: 'SIKRINGSRUM_ANT', type: 'integer'},
      { name: 'FREDNING_KODE', type: 'integer'},
      { name: 'BevarVaerdig', type: 'integer'},
      { name: 'UdlejForhold1', type: 'integer'},
      { name: 'HusLeje', type: 'integer'},
      { name: 'HuslejeOplysDato', type: 'string'},
      { name: 'SagsType', type: 'integer'},
      { name: 'BygPktNoejagtigKls', type: 'string'},
      { name: 'BygPkt_id', type: 'uuid'},
      { name: 'FOT_id', type: 'integer'},
      { name: 'StormRaadPaalaeg', type: 'integer'},
      { name: 'StormRaadPaalaegDato', type: 'string'},
      { name: 'BygSkadeForsikSelskab', type: 'string'},
      { name: 'BygSkadeForsikSelskabDato', type: 'string'},
      { name: 'KomFelt1', type: 'string'},
      { name: 'KomFelt2', type: 'string'},
      { name: 'KomFelt3', type: 'string'},
      { name: 'KomFelt4', type: 'string'},
      { name: 'KomFelt5', type: 'string'},
      { name: 'KomFelt6', type: 'string'},
      { name: 'JourNr', type: 'string'},
      { name: 'ESDH_Ref', type: 'string'},
      { name: 'SikKlas', type: 'integer'},
      { name: 'OPRET_TS', type: 'timestamp'},
      { name: 'AENDR_TS', type: 'timestamp'},
      { name: 'Aendr_Funk', type: 'string'},
      { name: 'Ophoert_ts', type: 'timestamp'},
      { name: 'Kommune_id', type: 'uuid'},
      { name: 'KomKode', type: 'integer'},
      { name: 'eRef', type: 'uuid'},
      { name: 'Landsejerlavkode', type: 'integer' },
      { name: 'KomEjerlavKode', type: 'integer'},
      { name: 'MatrNr', type: 'string' },
      { name: 'ESREjdNr', type: 'integer'},
      { name: 'Matr_art_kode', type: 'integer'},
      { name: 'Delnr', type: 'string'},
      { name: 'Opdelingsnr', type: 'integer'},
      { name: 'BygSkadeOmfatFors', type: 'string'},
      { name: 'Gyldighedsdato', type: 'string'}
    ]
  }
};