DROP VIEW IF EXISTS adresser_mat_view CASCADE;

CREATE VIEW adresser_mat_view AS
  SELECT
    e.id,
    e.adgangsadresseid,
    e.objekttype,
    e.oprettet,
    e.ikraftfra,
    e.aendret,
    e.etage,
    e.doer,
    e.kilde,
    e.esdhReference,
    e.journalnummer,
    a.objekttype AS a_objekttype,
    a.oprettet   AS a_oprettet,
    a.aendret    AS a_aendret,
    a.ikraftfra  AS a_ikraftfra,
    a.kommunekode,
    a.vejkode,
    a.husnr         husnr,
    a.supplerendebynavn,
    a.postnr,
    a.ejerlavkode,
    a.matrikelnr,
    a.esrejendomsnr,
    a.adgangspunktid,
    a.etrs89oest,
    a.etrs89nord,
    a.noejagtighed,
    a.adgangspunktkilde,
    a.husnummerkilde,
    a.placering,
    a.tekniskstandard,
    a.tekstretning,
    a.adressepunktaendringsdato,
    a.geom,
    a.hoejde,
    a.navngivenvej_id,
    a.navngivenvejkommunedel_id,
    a.supplerendebynavn_id,
    a.darkommuneinddeling_id,
    a.adressepunkt_id,
    a.postnummer_id,
    a.postnrnavn,
    a.vejnavn,
    a.adresseringsvejnavn,
    a.ejerlavnavn,
    a.stormodtagerpostnr,
    a.stormodtagerpostnrnavn,
    a.vejpunkt_id,
    a.vejpunkt_kilde,
    a.vejpunkt_tekniskstandard,
    a.vejpunkt_noejagtighedsklasse,
    a.vejpunkt_geom

  FROM enhedsadresser e
    JOIN adgangsadresser_mat a ON e.adgangsadresseid = a.id;
