DROP VIEW IF EXISTS wfs_adresser2 CASCADE;

CREATE OR REPLACE VIEW wfs_adresser2 AS
  SELECT
    id::varchar             AS "id",
    objekttype AS status,
    etage,
    doer                      AS "doer",
    oprettet,
    ikraftfra               AS "ikrafttraedelsesdato",
    aendret,
    adgangsadresseid,
    kommunekode,
    vejkode,
    vejnavn,
    formatHusnr(husnr) as husnr,
    supplerendebynavn,
    postnr,
    postnrnavn,
    jordstykke_ejerlavkode as ejerlavkode,
    jordstykke_ejerlavnavn as ejerlavnavn,
    jordstykke_matrikelnr as matrikelnr,
    jordstykke_esrejendomsnr as esrejendomsnr,
    a_oprettet                AS "adgangsadresse_oprettet",
    a_ikraftfra               AS "adgangsadresse_ikrafttraedelsesdato",
    a_aendret                 AS "adgangsadresse_aendret",
    a_objekttype AS adgangsadresse_status,
    oest                AS "etrs89koordinat_oest",
    nord                AS "etrs89koordinat_nord",
    noejagtighed              AS "noejagtighed",
    kilde,
    tekniskstandard,
    tekstretning,
    ddkn_m100,
    ddkn_km1,
    ddkn_km10,
    adressepunktaendringsdato AS "adressepunktaendringsdato",
    round((COALESCE(tekstretning, 200) * 0.9 + 360 + 90))::INTEGER % 180 - 90 AS "tekstretninggrader",
    vejpunkt_id,
    vejpunkt_kilde,
    vejpunkt_noejagtighedsklasse as "vejpunkt_nøjagtighed",
    vejpunkt_tekniskstandard,
    geom
  FROM Adresser;
