
\set ON_ERROR_STOP on
\set ECHO queries

ALTER TABLE adgangsadresser DISABLE TRIGGER ALL;
ALTER TABLE enhedsadresser DISABLE TRIGGER ALL;
ALTER TABLE postnumre DISABLE TRIGGER ALL;
ALTER TABLE vejstykker DISABLE TRIGGER ALL;
