DROP INDEX stednavne_adgadr_changes_stednavn_id_adgangsadresse_id_chan_idx;
CREATE INDEX ON stedtilknytninger(stedid, adgangsadresseid, txid desc nulls last, changeid desc nulls last);
DROP VIEW adgangsadresserview cascade;
DROP VIEW adresser cascade;
DROP VIEW wms_adgangsadresser cascade;
DROP VIEW wms_housenumber_inspire cascade;
DROP VIEW adresser_mat_view;
DROP VIEW dar1_adgangsadresser_view CASCADE;
DROP VIEW adgangsadresser_mat_view CASCADE;
DROP VIEW adresser_mat_view CASCADE;
ALTER TABLE adgangsadresser alter column tekstretning set data type numeric(5,2);
ALTER TABLE adgangsadresser_changes alter column tekstretning set data type numeric(5,2);
ALTER TABLE adgangsadresser_mat alter column tekstretning set data type numeric(5,2);
ALTER TABLE adgangsadresser_mat_changes alter column tekstretning set data type numeric(5,2);
ALTER TABLE adresser_mat alter column tekstretning set data type numeric(5,2);
ALTER TABLE adresser_mat_changes alter column tekstretning set data type numeric(5,2);