ALTER TABLE vejstykker ADD COLUMN geom geometry(MULTILINESTRINGZ, 25832);
ALTER TABLE vejstykker_history ADD COLUMN geom geometry(MULTILINESTRINGZ, 25832);
CREATE INDEX ON vejstykker USING GIST(geom);
