module.exports = [
  require('./adgangsadresse-page'),
  require('./adresse-page'),
  require('./afstemningsområde-page'),
  require('./autocomplete-page'),
  require('./bebyggelse-page'),
  require('./bygning-page'),
  require('./ejerlav-page'),
  require("./jordstykke-page"),
  require('./kommune-page'),
  require('./menighedsrådsafstemningsområde-page'),
  require('./navngivenvej-page'),
  ... require('./ois-pages')('public'),
  ... require('./ois-pages')('full'),
  require('./opstillingskreds-page'),
  require('./politikreds-page'),
  require('./postnummer-page'),
  require('./region-page'),
  require('./replikering-page'),
  require('./replikering-old-page'),
  require('./retskreds-page'),
  require('./sogn-page'),
  require('./stednavn-page'),
  require('./stednavn2-page'),
  require('./sted-page'),
  require('./stednavntype-page'),
  require('./storkreds-page'),
  require('./supplerendebynavn-page'),
  require('./supplerendebynavn2-page'),
  require('./valglandsdel-page'),
  require('./vejnavn-page'),
  require('./vejstykke-page')
];
