module.exports = [
  require('./adgangsadresse-page'),
  require('./adresse-page'),
  require('./autocomplete-page'),
  require('./bebyggelse-page'),
  require('./ejerlav-page'),
  require("./jordstykke-page"),
  require('./kommune-page'),
  ... require('./ois-pages')('public'),
  ... require('./ois-pages')('full'),
  require('./opstillingskreds-page'),
  require('./politikreds-page'),
  require('./postnummer-page'),
  require('./region-page'),
  require('./replikering-page'),
  require('./retskreds-page'),
  require('./senesteSekvensnummer-page'),
  require('./sogn-page'),
  require('./stednavn-page'),
  require('./stednavntype-page'),
  require('./storkreds-page'),
  require('./supplerendebynavn-page'),
  require('./valglandsdel-page'),
  require('./vejnavn-page'),
  require('./vejstykke-page'),
  require('./vejstykkepostnummerrelation-page'),
  require('./zone-page')
];
