version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - bash ci/run-ci.sh
  post_build:
    commands:
      - docker push 587758073017.dkr.ecr.eu-west-1.amazonaws.com/dawa:latest