version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - cd scripts
      - npm install
      - cd ..
  build:
    commands:
      - scripts/ci/run-ci.js
  post_build:
    commands:
      - scripts/ci/upload-server-ecr.js