require('./adgangsadresse/nameAndKey');
require('./adresse/nameAndKey');
require('./temaer/namesAndKeys');
require('./postnummer/nameAndKey');
require('./supplerendebynavn/nameAndKey');
require('./vejnavn/nameAndKey');
require('./vejstykke/nameAndKey');
require('./ejerlav/nameAndKey');
require('./tematilknytninger/namesAndKeys');