"use strict";

require('./adgangsadresse/resources');
require('./adresse/resources');
require('./datavask/resources');
require('./flats/resources');
require('./history/resources');
require('./postnummer/resources');
require('./temaer/resources');
require('./supplerendebynavn-old/resources');
require('./vejnavn/resources');
require('./vejstykke/resources');
require('./ejerlav/resources');
require('./navngivenvej/resources');
require('./replikering/events/resources');
require('./replikering/sekvensnummer/senesteSekvensnummer');
require('./replikering/udtraek/resources');
require('./replikering/udtraek/combinedResource');
require('./replikering/events/combinedResource');
require('./replikering/transactions/resources');
require('./replikering/model/datamodelResource');
require('./consistency');
require('./autocomplete/autocomplete.js');
require('./ois/resources');
require('./stednavn/resources');
require('./bebyggelse/resources');
require('./stednavntype/resources');
