"use strict";

require('./adgangsadresse/resources');
require('./adresse/resources');
require('./datavask/resources');
require('./flats/resources');
require('./history/resources');
require('./postnummer/resources');
require('./temaer/resources');
require('./supplerendebynavn/resources');
require('./vejnavn/resources');
require('./vejstykke/resources');
require('./ejerlav/resources');
require('./navngivenvej/resources');
require('./replikering/events/resources');
require('./replikering/sekvensnummer/senesteSekvensnummer');
require('./replikering/udtraek/resources');
require('./consistency');
require('./autocomplete/autocomplete.js');
require('./ois/resources');
