"use strict";

module.exports = {
  grund: {
    oisTable: 'CO40000T',
    key: ['Grund_id'],
    fields: [
         { name: 'ois_id', oisType: 'int', public: true},
         { name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Grund_id', oisType: 'uniqueidentifier', public: true },
         { name: 'Kommune_id', oisType: 'uniqueidentifier', public: true },
         { name: 'ESREjdNr', oisType: 'char', oisLength: 6, public: true },
         { name: 'ObjStatus', oisType: 'tinyint', public: true },
         { name: 'NyByg', oisType: 'tinyint' },
         { name: 'CRUD_ID', oisType: 'bigint' },
         { name: 'Cs_Crud_id', oisType: 'bigint' },
         { name: 'Byggesag_id', oisType: 'uniqueidentifier' },
         { name: 'GrundStam_id', oisType: 'uniqueidentifier' },
         { name: 'MatrSFE_id', oisType: 'bigint', public: true },
         { name: 'AdgAdr_id', oisType: 'uniqueidentifier', public: true },
         { name: 'GRU_Afloeb_Kode', oisType: 'varchar', oisLength: 3 },
         { name: 'GRU_Afloeb_Tillad', oisType: 'varchar', oisLength: 3 },
         { name: 'GRU_VandForsy_Kode', oisType: 'tinyint' },
         { name: 'GRU_SagType', oisType: 'char', oisLength: 1 },
         { name: 'KomFelt1', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt2', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt3', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt4', oisType: 'int' },
         { name: 'KomFelt5', oisType: 'int' },
         { name: 'KomFelt6', oisType: 'int' },
         { name: 'JourNr', oisType: 'varchar', oisLength: 60 },
         { name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200 },
         { name: 'SikKlas', oisType: 'tinyint' },
         { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
         { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'GruMdlSplvnd', oisType: 'smallint' },
         { name: 'GruPbFrbRens', oisType: 'smallint' },
         { name: 'GruPbFrbRensDato', oisType: 'varchar', oisLength: 26 },
         { name: 'GruTilUdtr', oisType: 'smallint' },
         { name: 'GruTilUdtrDato', oisType: 'varchar', oisLength: 26 },
         { name: 'GruTilAltAfld', oisType: 'smallint' },
         { name: 'GruTilAltAfldDato', oisType: 'varchar', oisLength: 26 }
    ],
    derivedFields: []
  },
  bygning: {
    oisTable: 'CO40100T',
    key: ['Bygning_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Bygning_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Bygningsnr', oisType: 'char', oisLength: 3, public: true},
      {name: 'ObjStatus', oisType: 'tinyint', public: true},
      {name: 'NyByg', oisType: 'tinyint'},
      {name: 'Crud_id', oisType: 'bigint'},
      {name: 'Grund_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Byggesag_id', oisType: 'uniqueidentifier'},
      {name: 'BygStam_id', oisType: 'uniqueidentifier'},
      {name: 'AdgAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'BYG_ANVEND_KODE', oisType: 'smallint'},
      {name: 'Klassifikation', oisType: 'smallint'},
      {name: 'AnvKonvKilde', oisType: 'smallint'},
      {name: 'AntLejMKoekken', oisType: 'int'},
      {name: 'AntLejUKoekken', oisType: 'int'},
      {name: 'OPFOERELSE_AAR', oisType: 'smallint'},
      {name: 'OMBYG_AAR', oisType: 'smallint'},
      {name: 'MIDL_OPRET_KODE', oisType: 'tinyint'},
      {name: 'UdloebDatoMidl', oisType: 'varchar', oisLength: 26},
      {name: 'BYG_VANDFORSY_KODE', oisType: 'tinyint'},
      {name: 'BYG_AFLOEB_KODE', oisType: 'varchar', oisLength: 3},
      {name: 'BYG_AFLOEB_TILL', oisType: 'varchar', oisLength: 3},
      {name: 'YDERVAEG_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'TAG_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'SuppYderVaegMat', oisType: 'varchar', oisLength: 2},
      {name: 'SuppTagDaekMat', oisType: 'varchar', oisLength: 2},
      {name: 'AsbestMateriale', oisType: 'char', oisLength: 1},
      {name: 'KILDE_MATR_KODE', oisType: 'char', oisLength: 1},
      {name: 'BYG_ARL_SAML', oisType: 'int'},
      {name: 'BYG_BOLIG_ARL_SAML', oisType: 'int'},
      {name: 'ERHV_ARL_SAML', oisType: 'int'},
      {name: 'BYG_BEBYG_ARL', oisType: 'int'},
      {name: 'GARAGE_INDB_ARL', oisType: 'int'},
      {name: 'CARPORT_INDB_ARL', oisType: 'int'},
      {name: 'UDHUS_INDB_ARL', oisType: 'int'},
      {name: 'UDESTUE_ARL', oisType: 'int'},
      {name: 'LukOverdaekAreal', oisType: 'int'},
      {name: 'AFFALDSRUM_ARL', oisType: 'int'},
      {name: 'ANDET_ARL', oisType: 'int'},
      {name: 'OverdaekAreal', oisType: 'int'},
      {name: 'AabenOverdaekAreal', oisType: 'int'},
      {name: 'AdgangsAreal', oisType: 'int'},
      {name: 'Carport_Princip', oisType: 'char', oisLength: 1},
      {name: 'KILDE_ARL_KODE', oisType: 'tinyint'},
      {name: 'ETAGER_ANT', oisType: 'smallint'},
      {name: 'ETAGER_AFVIG_KODE', oisType: 'tinyint'},
      {name: 'VARMEINSTAL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'OPVARMNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'VARME_SUPPL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'SIKRINGSRUM_ANT', oisType: 'smallint'},
      {name: 'FREDNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'BevarVaerdig', oisType: 'varchar', oisLength: 200},
      {name: 'UdlejForhold1', oisType: 'char', oisLength: 1},
      {name: 'HusLeje', oisType: 'int'},
      {name: 'HuslejeOplysDato', oisType: 'varchar', oisLength: 26},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'BygPktNoejagtigKls', oisType: 'varchar', oisLength: 2, public: true},
      {name: 'BygPkt_id', oisType: 'uniqueidentifier', public: true},
      {name: 'FOT_id', oisType: 'int'},
      {name: 'StormRaadPaalaeg', oisType: 'tinyint'},
      {name: 'StormRaadPaalaegDato', oisType: 'varchar', oisLength: 26},
      {name: 'BygSkadeForsikSelskab', oisType: 'char', oisLength: 2},
      {name: 'BygSkadeForsikSelskabDato', oisType: 'varchar', oisLength: 26},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Kommune_id', oisType: 'uniqueidentifier', public: true},
      {name: 'KomKode', oisType: 'char', oisLength: 4, public: true},
      {name: 'eRef', oisType: 'uniqueidentifier'},
      {name: 'Landsejerlavkode', oisType: 'int', public: true},
      {name: 'KomEjerlavKode', oisType: 'smallint', public: true},
      {name: 'MatrNr', oisType: 'varchar', oisLength: 10, public: true},
      {name: 'ESREjdNr', oisType: 'char', oisLength: 6, public: true},
      {name: 'Matr_art_kode', oisType: 'smallint'},
      {name: 'Delnr', oisType: 'varchar', oisLength: 3},
      {name: 'Opdelingsnr', oisType: 'varchar', oisLength: 3},
      {name: 'BygSkadeOmfatFors', oisType: 'varchar', oisLength: 2},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26}
    ],
    derivedFields: []
  },
  opgang: {
    oisTable: 'CO40200T',
    key: ['Opgang_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Opgang_id', oisType: 'uniqueidentifier', public: true},
      {name: 'AdgAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'ObjStatus', oisType: 'tinyint', public: true},
      {name: 'NyByg', oisType: 'tinyint'},
      {name: 'Crud_id', oisType: 'bigint'},
      {name: 'ByggeSag_id', oisType: 'uniqueidentifier'},
      {name: 'OpgStam_id', oisType: 'uniqueidentifier'},
      {name: 'Bygning_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Elevator', oisType: 'tinyint'},
      {name: 'DataFelt1', oisType: 'int'},
      {name: 'DataFelt2', oisType: 'char', oisLength: 1},
      {name: 'DataFelt3', oisType: 'char', oisLength: 1},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26, public: true}
    ],
    derivedFields: []
  },
  enhedopgang: {
    oisTable: 'CO40300T',
    key: ['EnhedOpgang_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'EnhedOpgang_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Opgang_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Enhed_id', oisType: 'uniqueidentifier', public: true},
      {name: 'PrimaerIndg', oisType: 'tinyint', public: true},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
    ],
    derivedFields: []
  },
  enhed: {
    oisTable: 'CO40400T',
    key: ['Enhed_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Enhed_id', oisType: 'uniqueidentifier', public: true},
      {name: 'ObjStatus', oisType: 'tinyint', public: true},
      {name: 'Nybyg', oisType: 'tinyint'},
      {name: 'CRUD_ID', oisType: 'bigint'},
      {name: 'ByggeSag_id', oisType: 'uniqueidentifier'},
      {name: 'EnhedStam_id', oisType: 'uniqueidentifier'},
      {name: 'EnhAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Etage_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Opgang_id', oisType: 'uniqueidentifier', public: true},
      {name: 'HenvEnh_id', oisType: 'uniqueidentifier'},
      {name: 'REF_Enhed_id', oisType: 'uniqueidentifier'},
      {name: 'ENH_ANVEND_KODE', oisType: 'smallint'},
      {name: 'Klassifikation', oisType: 'smallint'},
      {name: 'AnvKonvKilde', oisType: 'tinyint'},
      {name: 'BOLIGTYPE_KODE', oisType: 'char', oisLength: 1},
      {name: 'BOLIG_KONDEM', oisType: 'tinyint'},
      {name: 'IdentOpretDato', oisType: 'varchar', oisLength: 26},
      {name: 'ENH_ARL_SAML', oisType: 'int'},
      {name: 'BEBO_ARL', oisType: 'int'},
      {name: 'ENH_ERHV_ARL', oisType: 'int'},
      {name: 'KILDE_ARL_KODE', oisType: 'tinyint'},
      {name: 'VAERELSE_ANT', oisType: 'smallint'},
      {name: 'TOILET_KODE', oisType: 'char', oisLength: 1},
      {name: 'BAD_KODE', oisType: 'char', oisLength: 1},
      {name: 'KOEKKEN_KODE', oisType: 'char', oisLength: 1},
      {name: 'ENERGI_KODE', oisType: 'char', oisLength: 1},
      {name: 'ENH_UDLEJ1_KODE', oisType: 'char', oisLength: 1},
      {name: 'HusLeje', oisType: 'int'},
      {name: 'HuslejeOplysDato', oisType: 'varchar', oisLength: 26},
      {name: 'AndetAreal', oisType: 'int'},
      {name: 'GodkTomBoligGL', oisType: 'tinyint'},
      {name: 'LOVLIG_ANVEND_KODE', oisType: 'char', oisLength: 1},
      {name: 'DispTidsbegraensetDato', oisType: 'varchar', oisLength: 26},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'ENH_DEL_IBRUG_DATO', oisType: 'varchar', oisLength: 26},
      {name: 'ENH_UDLEJ2_KODE', oisType: 'char', oisLength: 1},
      {name: 'OFF_STOETTE_KODE', oisType: 'char', oisLength: 2},
      {name: 'IndflytDato', oisType: 'varchar', oisLength: 26},
      {name: 'GodkTomBolig', oisType: 'smallint'},
      {name: 'VARMEINSTAL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'OPVARMNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'VARME_SUPPL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'FaellesAdgArealAndel', oisType: 'int'},
      {name: 'AabenOverdaekAreal', oisType: 'int'},
      {name: 'LukOverdaekAreal', oisType: 'int'},
      {name: 'VAER_ERHV_ANT', oisType: 'smallint'},
      {name: 'AntVandskylToilleter', oisType: 'smallint'},
      {name: 'AntBadevaerelser', oisType: 'smallint'},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26, public: true}
    ],
    derivedFields: []
  },
  etage: {
    oisTable: 'CO40500T',
    key: ['Etage_id'],
    fields: [
         { name: 'ois_id', oisType: 'int' , public: true},
         { name: 'ois_ts', oisType: 'varchar', oisLength: 26 , public: true },
         { name: 'Etage_id', oisType: 'uniqueidentifier' , public: true},
         { name: 'Etagebetegn', oisType: 'varchar', oisLength: 2 , public: true },
         { name: 'ObjStatus', oisType: 'tinyint', public: true },
         { name: 'NyByg', oisType: 'tinyint' },
         { name: 'CRUD_ID', oisType: 'bigint' },
         { name: 'ByggeSag_id', oisType: 'uniqueidentifier' },
         { name: 'EtageStam_id', oisType: 'uniqueidentifier' },
         { name: 'Bygning_id', oisType: 'uniqueidentifier', public: true},
         { name: 'SamletAreal', oisType: 'int' },
         { name: 'TAGETAGE_ARL_UDNYT', oisType: 'int' },
         { name: 'KAELDER_ARL_U_125M', oisType: 'int' },
         { name: 'KaeldArlLovigBebo', oisType: 'int' },
         { name: 'AdgangsAreal', oisType: 'int' },
         { name: 'SagsType', oisType: 'char', oisLength: 1 },
         { name: 'KomFelt1', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt2', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt3', oisType: 'varchar', oisLength: 3 },
         { name: 'KomFelt4', oisType: 'int' },
         { name: 'KomFelt5', oisType: 'int' },
         { name: 'KomFelt6', oisType: 'int' },
         { name: 'JourNr', oisType: 'varchar', oisLength: 60 },
         { name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200 },
         { name: 'SikKlas', oisType: 'tinyint' },
         { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
         { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'EtageType', oisType: 'tinyint' },
         { name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26, public: true }
    ],
    derivedFields: []
  },
  tekniskanlaeg: {
    oisTable: 'CO40700T',
    key: ['Tekniskanlaeg_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Tekniskanlaeg_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Tek_Nr', oisType: 'smallint'},
      {name: 'ObjStatus', oisType: 'tinyint', public: true},
      {name: 'NyByg', oisType: 'tinyint'},
      {name: 'ByggeSag_id', oisType: 'uniqueidentifier'},
      {name: 'TekAnlaegStam_id', oisType: 'uniqueidentifier'},
      {name: 'CRUD_ID', oisType: 'bigint'},
      {name: 'Bygning_id', oisType: 'uniqueidentifier', public: true},
      {name: 'AdgAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'TilnaermetAdr', oisType: 'tinyint'},
      {name: 'BygPkt_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Klassifikation', oisType: 'smallint'},
      {name: 'FabrikatType', oisType: 'varchar', oisLength: 50},
      {name: 'ExtDB', oisType: 'varchar', oisLength: 50},
      {name: 'ExtNoegle', oisType: 'varchar', oisLength: 50},
      {name: 'Etableringsaar', oisType: 'smallint'},
      {name: 'SenestTilOmBygAar', oisType: 'smallint'},
      {name: 'StoerrelsesKlasse', oisType: 'varchar', oisLength: 4},
      {name: 'OlieTankPlacer', oisType: 'char', oisLength: 1},
      {name: 'Slojfning', oisType: 'varchar', oisLength: 2},
      {name: 'FabrikatNr', oisType: 'varchar', oisLength: 10},
      {name: 'TypegodkNr', oisType: 'varchar', oisLength: 10},
      {name: 'Stoerrelse', oisType: 'int'},
      {name: 'OlietankKilde', oisType: 'tinyint'},
      {name: 'Type', oisType: 'tinyint'},
      {name: 'Indhold', oisType: 'tinyint'},
      {name: 'SloejfFristDato', oisType: 'varchar', oisLength: 26},
      {name: 'RumfangM3', oisType: 'int'},
      {name: 'Areal', oisType: 'int'},
      {name: 'Hoejde', oisType: 'int'},
      {name: 'EffektKW', oisType: 'int'},
      {name: 'FredningsStatus', oisType: 'varchar', oisLength: 2},
      {name: 'BygPktNoejagtigKls', oisType: 'varchar', oisLength: 2},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Kommune_id', oisType: 'uniqueidentifier', public: true},
      {name: 'KomKode', oisType: 'char', oisLength: 4, public: true},
      {name: 'eRef', oisType: 'uniqueidentifier'},
      {name: 'LandsejerlavKode', oisType: 'int', public: true},
      {name: 'KomEjerlavKode', oisType: 'smallint', public: true},
      {name: 'MatrNr', oisType: 'varchar', oisLength: 10, public: true},
      {name: 'Grund_id', oisType: 'uniqueidentifier', public: true},
      {name: 'ESREjdNr', oisType: 'char', oisLength: 6, public: true},
      {name: 'Matr_art_kode', oisType: 'smallint',},
      {name: 'Delnr', oisType: 'varchar', oisLength: 3},
      {name: 'Opdelingsnr', oisType: 'varchar', oisLength: 3},
      {name: 'Fabrikationsaar', oisType: 'smallint'},
      {name: 'Materiale', oisType: 'varchar', oisLength: 2},
      {name: 'InvendigBeskyt', oisType: 'varchar', oisLength: 2},
      {name: 'InvendigBeskytDato', oisType: 'varchar', oisLength: 26},
      {name: 'CETypegodk', oisType: 'varchar', oisLength: 50},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26},
      {name: 'SloejfningAar', oisType: 'smallint'}
    ],
    derivedFields: []
  },
  ejerskab: {
    oisTable: 'CO41000T',
    key: ['Ejerskab_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Ejerskab_id', oisType: 'uniqueidentifier', public: true},
      {name: 'EntitetsType', oisType: 'tinyint', public: true},
      {name: 'BbrId', oisType: 'uniqueidentifier', public: true},
      {name: 'Kommune_id', oisType: 'uniqueidentifier', public: true},
      {name: 'ESREjdNr', oisType: 'char', oisLength: 6, public: true},
      {name: 'eRef', oisType: 'uniqueidentifier'},
      {name: 'MereEnd1EjerLej', oisType: 'char', oisLength: 1},
      {name: 'EjerlejNr', oisType: 'varchar', oisLength: 8},
      {name: 'ESRArtskode', oisType: 'smallint'},
      {name: 'TinglystAreal', oisType: 'int'},
      {name: 'EJERFORHOLD_KODE', oisType: 'smallint'},
      {name: 'ObjStatus', oisType: 'tinyint', public: true},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true}
    ],
    derivedFields: []
  },
  kommune: {
    oisTable: 'CO41100T',
    key: ['Kommune_id'],
    fields: [
      { name: 'ois_id', oisType: 'int', public: true},
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true },
      { name: 'Kommune_id', oisType: 'uniqueidentifier', public: true },
      { name: 'KomKode', oisType: 'char', oisLength: 4, public: true },
      { name: 'KomNavn', oisType: 'varchar', oisLength: 40, public: true },
      { name: 'BbrNavn', oisType: 'varchar', oisLength: 40, public: true },
      { name: 'BbrKontor', oisType: 'varchar', oisLength: 40, public: true },
      { name: 'BbrAdr', oisType: 'varchar', oisLength: 40, public: true },
      { name: 'BbrPost', oisType: 'varchar', oisLength: 40, public: true },
      { name: 'BbrTlfNr', oisType: 'varchar', oisLength: 20, public: true },
      { name: 'BbrEmail', oisType: 'varchar', oisLength: 60, public: true },
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true}
    ],
    derivedFields: []
  },
  enhedenhedsadresse: {
    oisTable: 'CO42200T',
    key: ['EnhEnhAdr_id'],
    fields: [
      {name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'EnhEnhAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'EnhAdr_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Enhed_id', oisType: 'uniqueidentifier', public: true},
      {name: 'PrimaerAdr', oisType: 'tinyint', public: true},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
    ],
    derivedFields: []
  },
  entitet: {
    oisTable: 'CO42500T',
    key: ['Entitet_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Entitet_id', oisType: 'uniqueidentifier' },
      { name: 'Navn', oisType: 'varchar', oisLength: 30 },
      { name: 'Beskrivelse', oisType: 'varchar', oisLength: 200 },
      { name: 'Kortnavn', oisType: 'varchar', oisLength: 5 },
      { name: 'Obligatorisk', oisType: 'tinyint' },
      { name: 'Administrativ', oisType: 'tinyint' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 },
    ],
    derivedFields: []
  },
  felt: {
    oisTable: 'CO42600T',
    key: ['Felt_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Felt_id', oisType: 'uniqueidentifier' },
      { name: 'Entitet_id', oisType: 'uniqueidentifier' },
      { name: 'FELT_NAVN', oisType: 'varchar', oisLength: 60 },
      { name: 'FELT_BESKRIVELSE', oisType: 'varchar', oisLength: 200 },
      { name: 'Datatype_id', oisType: 'uniqueidentifier' },
      { name: 'BbrNr', oisType: 'char', oisLength: 8 },
      { name: 'Type', oisType: 'tinyint' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 },
    ],
    derivedFields: []
  },
  datatype: {
    oisTable: 'CO42700T',
    key: ['Datatype_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Datatype_id', oisType: 'uniqueidentifier' },
      { name: 'Datatype', oisType: 'varchar', oisLength: 20 },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 }
    ],
    derivedFields: []
  },
  kodetype: {
    oisTable: 'CO42800T',
    key: ['Kodetype_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Kodetype_id', oisType: 'uniqueidentifier' },
      { name: 'KodeType_Nr', oisType: 'smallint' },
      { name: 'Beskrivelse', oisType: 'varchar', oisLength: 100 },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 }
    ],
    derivedFields: []
  },
  kodefelt: {
    oisTable: 'CO42900T',
    key: ['Kodefelt_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Kodefelt_id', oisType: 'uniqueidentifier' },
      { name: 'Felt_id', oisType: 'uniqueidentifier' },
      { name: 'Kodetype_id', oisType: 'uniqueidentifier' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 }
    ],
    derivedFields: []
  },
  kode: {
    oisTable: 'CO43000T',
    key: ['Kode_id'],
    fields: [   { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Kode_id', oisType: 'uniqueidentifier' },
      { name: 'Kodefelt_id', oisType: 'uniqueidentifier' },
      { name: 'KODE_VAERDI', oisType: 'varchar', oisLength: 10 },
      { name: 'KODE_TEKST', oisType: 'varchar', oisLength: 500 },
      { name: 'Udgaaet', oisType: 'tinyint' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 },
    ],
    derivedFields: []
  },
  bygningspunkt: {
    oisTable: 'CO43100T',
    key: ['BygPkt_id'],
    fields: [{name: 'ois_id', oisType: 'int', public: true},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'BygPkt_id', oisType: 'uniqueidentifier', public: true},
      {name: 'Kommune_id', oisType: 'uniqueidentifier', public: true},
      {name: 'PktRevDato', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'KoorOest', oisType: 'decimal', oisLength: 9, public: true},
      {name: 'KoorNord', oisType: 'decimal', oisLength: 9, public: true},
      {name: 'KoorSystem', oisType: 'tinyint', public: true},
      {name: 'TxtRetn', oisType: 'decimal', oisLength: 5, public: true},
      {name: 'TxtPlacer', oisType: 'char', oisLength: 1, public: true},
      {name: 'DDKNcelle100m', oisType: 'varchar', oisLength: 15, public: true},
      {name: 'DDKNcelle1km', oisType: 'varchar', oisLength: 15, public: true},
      {name: 'DDKNcelle10km', oisType: 'varchar', oisLength: 15, public: true},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true},
      {name: 'BygPktKilde', oisType: 'tinyint', public: true},
    ],
    derivedFields: [{
      name: 'geom',
      postgresType: 'geometry(Point,25832)',
      compute: row => {
        const x = row.KoorOest;
        const y = row.KoorNord;
        if (x && y) {
          return `SRID=25832;POINT(${x} ${y})`;
        }
        else {
          return null;
        }
      },
      public: true
    }]
  },
  matrikelreference: {
    oisTable: 'CO43300T',
    key: ['ois_id'],
    fields: [
         { name: 'ois_id', oisType: 'int', public: true},
         { name: 'ois_ts', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Grund_id', oisType: 'uniqueidentifier', public: true },
         { name: 'Kommune_id', oisType: 'uniqueidentifier', public: true },
         { name: 'KomKode', oisType: 'char', oisLength: 4, public: true },
         { name: 'eRef', oisType: 'uniqueidentifier' },
         { name: 'LandsejerlavKode', oisType: 'int', public: true },
         { name: 'KomEjerlav_id', oisType: 'uniqueidentifier', public: true },
         { name: 'MatrNr', oisType: 'varchar', oisLength: 10, public: true },
         { name: 'Udskrivning', oisType: 'char', oisLength: 1, public: true },
         { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26, public: true },
         { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
         { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26, public: true },
    ],
    derivedFields: []
  }
};
