"use strict";

module.exports = {
  bygning: {
    oisTable: 'CO40100T',
    key: ['Bygning_id'],
    fields: [
      {name: 'ois_id', oisType: 'int'},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      {name: 'Bygning_id', oisType: 'uniqueidentifier'},
      {name: 'bygningsnr', oisType: 'char', oisLength: 3},
      {name: 'ObjStatus', oisType: 'tinyint'},
      {name: 'NyByg', oisType: 'tinyint'},
      {name: 'Crud_id', oisType: 'bigint'},
      {name: 'Grund_id', oisType: 'uniqueidentifier'},
      {name: 'Byggesag_id', oisType: 'uniqueidentifier'},
      {name: 'BygStam_id', oisType: 'uniqueidentifier'},
      {name: 'AdgAdr_id', oisType: 'uniqueidentifier'},
      {name: 'BYG_ANVEND_KODE', oisType: 'smallint'},
      {name: 'Klassifikation', oisType: 'smallint'},
      {name: 'AnvKonvKilde', oisType: 'smallint'},
      {name: 'AntLejMKoekken', oisType: 'int'},
      {name: 'AntLejUKoekken', oisType: 'int'},
      {name: 'OPFOERELSE_AAR', oisType: 'smallint'},
      {name: 'OMBYG_AAR', oisType: 'smallint'},
      {name: 'MIDL_OPRET_KODE', oisType: 'tinyint'},
      {name: 'UdloebDatoMidl', oisType: 'varchar', oisLength: 26},
      {name: 'BYG_VANDFORSY_KODE', oisType: 'tinyint'},
      {name: 'BYG_AFLOEB_KODE', oisType: 'varchar', oisLength: 3},
      {name: 'BYG_AFLOEB_TILL', oisType: 'varchar', oisLength: 3},
      {name: 'YDERVAEG_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'TAG_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'SuppYderVaegMat', oisType: 'varchar', oisLength: 2},
      {name: 'SuppTagDaekMat', oisType: 'varchar', oisLength: 2},
      {name: 'AsbestMateriale', oisType: 'char', oisLength: 1},
      {name: 'KILDE_MATR_KODE', oisType: 'char', oisLength: 1},
      {name: 'BYG_ARL_SAML', oisType: 'int'},
      {name: 'BYG_BOLIG_ARL_SAML', oisType: 'int'},
      {name: 'ERHV_ARL_SAML', oisType: 'int'},
      {name: 'BYG_BEBYG_ARL', oisType: 'int'},
      {name: 'GARAGE_INDB_ARL', oisType: 'int'},
      {name: 'CARPORT_INDB_ARL', oisType: 'int'},
      {name: 'UDHUS_INDB_ARL', oisType: 'int'},
      {name: 'UDESTUE_ARL', oisType: 'int'},
      {name: 'LukOverdaekAreal', oisType: 'int'},
      {name: 'AFFALDSRUM_ARL', oisType: 'int'},
      {name: 'ANDET_ARL', oisType: 'int'},
      {name: 'OverdaekAreal', oisType: 'int'},
      {name: 'AabenOverdaekAreal', oisType: 'int'},
      {name: 'AdgangsAreal', oisType: 'int'},
      {name: 'Carport_Princip', oisType: 'char', oisLength: 1},
      {name: 'KILDE_ARL_KODE', oisType: 'tinyint'},
      {name: 'ETAGER_ANT', oisType: 'smallint'},
      {name: 'ETAGER_AFVIG_KODE', oisType: 'tinyint'},
      {name: 'VARMEINSTAL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'OPVARMNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'VARME_SUPPL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'SIKRINGSRUM_ANT', oisType: 'smallint'},
      {name: 'FREDNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'BevarVaerdig', oisType: 'varchar', oisLength: 200},
      {name: 'UdlejForhold1', oisType: 'char', oisLength: 1},
      {name: 'HusLeje', oisType: 'int'},
      {name: 'HuslejeOplysDato', oisType: 'varchar', oisLength: 26},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'BygPktNoejagtigKls', oisType: 'varchar', oisLength: 2 },
      {name: 'BygPkt_id', oisType: 'uniqueidentifier'},
      {name: 'FOT_id', oisType: 'int'},
      {name: 'StormRaadPaalaeg', oisType: 'tinyint'},
      {name: 'StormRaadPaalaegDato', oisType: 'varchar', oisLength: 26},
      {name: 'BygSkadeForsikSelskab', oisType: 'char', oisLength: 2},
      {name: 'BygSkadeForsikSelskabDato', oisType: 'varchar', oisLength: 26},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
      {name: 'Kommune_id', oisType: 'uniqueidentifier'},
      {name: 'KomKode', oisType: 'char', oisLength: 4},
      {name: 'eRef', oisType: 'uniqueidentifier'},
      {name: 'Landsejerlavkode', oisType: 'int'},
      {name: 'KomEjerlavKode', oisType: 'smallint'},
      {name: 'MatrNr', oisType: 'varchar', oisLength: 10},
      {name: 'ESREjdNr', oisType: 'char', oisLength: 6},
      {name: 'Matr_art_kode', oisType: 'smallint'},
      {name: 'Delnr', oisType: 'varchar', oisLength: 3},
      {name: 'Opdelingsnr', oisType: 'varchar', oisLength: 3},
      {name: 'BygSkadeOmfatFors', oisType: 'varchar', oisLength: 2},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26}
    ]
  },
  opgang: {
    oisTable: 'CO40200T',
    key: ['Opgang_id'],
    fields: [
      {name: 'ois_id', oisType: 'int'},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      { name: 'Opgang_id', oisType: 'uniqueidentifier' },
      {name: 'AdgAdr_id', oisType: 'uniqueidentifier'},
      {name: 'ObjStatus', oisType: 'tinyint'},
      {name: 'NyByg', oisType: 'tinyint'},
      {name: 'Crud_id', oisType: 'bigint'},
      {name: 'ByggeSag_id', oisType: 'uniqueidentifier'},
      {name: 'OpgStam_id', oisType: 'uniqueidentifier'},
      {name: 'Bygning_id', oisType: 'uniqueidentifier'},
      {name: 'Elevator', oisType: 'tinyint'},
      {name: 'DataFelt1', oisType: 'int'},
      {name: 'DataFelt2', oisType: 'char', oisLength: 1},
      {name: 'DataFelt3', oisType: 'char', oisLength: 1},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLengt: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26}
    ]
  },
  enhedopgang: {
    oisTable: 'CO40300T',
    key: ['EnhedOpgang_id'],
    fields: [
      {name: 'ois_id', oisType: 'int'},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      {name: 'EnhedOpgang_id', oisType: 'uniqueidentifier'},
      {name: 'Opgang_id', oisType: 'uniqueidentifier'},
      {name: 'PrimaerIndg', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
    ]
  },
  enhed: {
    oisTable: 'CO40400T',
    key: ['Enhed_id'],
    fields: [
      {name: 'ois_id', oisType: 'int'},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      {name: 'Enhed_id', oisType: 'uniqueidentifier'},
      {name: 'ObjStatus', oisType: 'tinyint'},
      {name: 'Nybyg', oisType: 'tinyint'},
      {name: 'CRUD_ID', oisType: 'bigint'},
      {name: 'ByggeSag_id', oisType: 'uniqueidentifier'},
      {name: 'EnhedStam_id', oisType: 'uniqueidentifier'},
      {name: 'EnhAdr_id', oisType: 'uniqueidentifier'},
      {name: 'Etage_id', oisType: 'uniqueidentifier'},
      {name: 'Opgang_id', oisType: 'uniqueidentifier'},
      {name: 'HenvEnh_id', oisType: 'uniqueidentifier'},
      {name: 'REF_Enhed_id', oisType: 'uniqueidentifier'},
      {name: 'ENH_ANVEND_KODE', oisType: 'smallint'},
      {name: 'Klassifikation', oisType: 'smallint'},
      {name: 'AnvKonvKilde', oisType: 'tinyint'},
      {name: 'BOLIGTYPE_KODE', oisType: 'char', oisLength: 1},
      {name: 'BOLIG_KONDEM', oisType: 'tinyint'},
      {name: 'IdentOpretDato', oisType: 'varchar', oisLength: '26'},
      {name: 'ENH_ARL_SAML', oisType: 'int'},
      {name: 'BEBO_ARL', oisType: 'int'},
      {name: 'ENH_ERHV_ARL', oisType: 'int'},
      {name: 'KILDE_ARL_KODE', oisType: 'tinyint'},
      {name: 'VAERELSE_ANT', oisType: 'smallint'},
      {name: 'TOILET_KODE', oisType: 'char', oisLength: 1},
      {name: 'BAD_KODE', oisType: 'char', oisLength: 1},
      {name: 'KOEKKEN_KODE', oisType: 'char', oisLength: 1},
      {name: 'ENERGI_KODE', oisType: 'char', oisLength: 1},
      {name: 'ENH_UDLEJ1_KODE', oisType: 'char', oisLength: 1},
      {name: 'HusLeje', oisType: 'int'},
      {name: 'HuslejeOplysDato', oisType: 'varchar', oisLength: 26},
      {name: 'AndetAreal', oisType: 'int'},
      {name: 'GodkTomBoligGL', oisType: 'tinyint'},
      {name: 'LOVLIG_ANVEND_KODE', oisType: 'char', oisLength: 1},
      {name: 'DispTidsbegraensetDato', oisType: 'varchar', oisLength: 26},
      {name: 'SagsType', oisType: 'char', oisLength: 1},
      {name: 'ENH_DEL_IBRUG_DATO', oisType: 'varchar', oisLength: 26},
      {name: 'ENH_UDLEJ2_KODE', oisType: 'char', oisLength: 1},
      {name: 'OFF_STOETTE_KODE', oisType: 'char', oisLength: 2},
      {name: 'IndflytDato', oisType: 'varchar', oisLength: 26},
      {name: 'GodkTomBolig', oisType: 'smallint'},
      {name: 'VARMEINSTAL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'OPVARMNING_KODE', oisType: 'char', oisLength: 1},
      {name: 'VARME_SUPPL_KODE', oisType: 'varchar', oisLength: 2},
      {name: 'FaellesAdgArealAndel', oisType: 'int'},
      {name: 'AabenOverdaekAreal', oisType: 'int'},
      {name: 'LukOverdaekAreal', oisType: 'int'},
      {name: 'VAER_ERHV_ANT', oisType: 'smallint'},
      {name: 'AntVandskylToilleter', oisType: 'smallint'},
      {name: 'AntBadevaerelser', oisType: 'smallint'},
      {name: 'KomFelt1', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt2', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt3', oisType: 'varchar', oisLength: 3},
      {name: 'KomFelt4', oisType: 'int'},
      {name: 'KomFelt5', oisType: 'int'},
      {name: 'KomFelt6', oisType: 'int'},
      {name: 'JourNr', oisType: 'varchar', oisLength: 60},
      {name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200},
      {name: 'SikKlas', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLengt: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
      {name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26}
    ]
  },
  tekniskanlaeg: {
    oisTable: 'CO40700T',
    key: ['Tekniskanlaeg_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Tekniskanlaeg_id', oisType: 'uniqueidentifier' },
      { name: 'Tek_Nr', oisType: 'smallint' },
      { name: 'ObjStatus', oisType: 'tinyint' },
      { name: 'NyByg', oisType: 'tinyint' },
      { name: 'ByggeSag_id', oisType: 'uniqueidentifier' },
      { name: 'TekAnlaegStam_id', oisType: 'uniqueidentifier' },
      { name: 'CRUD_ID', oisType: 'bigint' },
      { name: 'Bygning_id', oisType: 'uniqueidentifier' },
      { name: 'AdgAdr_id', oisType: 'uniqueidentifier' },
      { name: 'TilnaermetAdr', oisType: 'tinyint' },
      { name: 'BygPkt_id', oisType: 'uniqueidentifier' },
      { name: 'Klassifikation', oisType: 'smallint' },
      { name: 'FabrikatType', oisType: 'varchar', oisLength: 50 },
      { name: 'ExtDB', oisType: 'varchar', oisLength: 50 },
      { name: 'ExtNoegle', oisType: 'varchar', oisLength: 50 },
      { name: 'Etableringsaar', oisType: 'smallint'},
      { name: 'SenestTilOmBygAar', oisType: 'smallint' },
      { name: 'StoerrelsesKlasse', oisType: 'varchar', oisLength: 4 },
      { name: 'OlieTankPlacer', oisType: 'char', oisLength: 1 },
      { name: 'Slojfning', oisType: 'varchar', oisLength: 2 },
      { name: 'FabrikatNr', oisType: 'varchar', oisLength: 10 },
      { name: 'TypegodkNr', oisType: 'varchar', oisLength: 10 },
      { name: 'Stoerrelse', oisType: 'int' },
      { name: 'OlietankKilde', oisType: 'tinyint' },
      { name: 'Type', oisType: 'tinyint' },
      { name: 'Indhold', oisType: 'tinyint' },
      { name: 'SloejfFristDato', oisType: 'varchar', oisLength: 26 },
      { name: 'RumfangM3', oisType: 'int' },
      { name: 'Areal', oisType: 'int' },
      { name: 'Hoejde', oisType: 'int' },
      { name: 'EffektKW', oisType: 'int' },
      { name: 'FredningsStatus', oisType: 'varchar', oisLength: 2 },
      { name: 'BygPktNoejagtigKls',  oisType: 'varchar', oisLength: 2 },
      { name: 'SagsType', oisType: 'char', oisLength: 1 },
      { name: 'KomFelt1', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt2', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt3', oisType: 'varchar', oisLength: 3 },
      { name: 'KomFelt4', oisType: 'int' },
      { name: 'KomFelt5', oisType: 'int' },
      { name: 'KomFelt6', oisType: 'int' },
      { name: 'JourNr', oisType: 'varchar', oisLength: 60 },
      { name: 'ESDH_Ref', oisType: 'varchar', oisLength: 200 },
      { name: 'SikKlas', oisType: 'tinyint' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Kommune_id', oisType: 'uniqueidentifier' },
      { name: 'KomKode', oisType: 'char', oisLength: 4},
      { name: 'eRef', oisType: 'uniqueidentifier' },
      { name: 'LandsejerlavKode', oisType: 'int' },
      { name: 'KomEjerlavKode', oisType: 'smallint' },
      { name: 'MatrNr', oisType: 'varchar', oisLength: 10 },
      { name: 'Grund_id', oisType: 'uniqueidentifier', },
      { name: 'ESREjdNr', oisType: 'char', oisLength: 6 },
      { name: 'Matr_art_kode', oisType: 'smallint', },
      { name: 'Delnr', oisType: 'varchar', oisLength: 3 },
      { name: 'Opdelingsnr', oisType: 'varchar', oisLength: 3 },
      { name: 'Fabrikationsaar', oisType: 'smallint' },
      { name: 'Materiale', oisType: 'varchar', oisLength: 2 },
      { name: 'InvendigBeskyt', oisType: 'varchar', oisLength: 2 },
      { name: 'InvendigBeskytDato', oisType: 'varchar', oisLength: 26 },
      { name: 'CETypegodk', oisType: 'varchar', oisLength: 50 },
      { name: 'Gyldighedsdato', oisType: 'varchar', oisLength: 26 },
      { name: 'SloejfningAar', oisType: 'smallint' }
    ]
  },
  ejerskab: {
    oisTable: 'CO41000T',
    key: ['Ejerskab_id'],
    fields: [
      { name: 'ois_id', oisType: 'int' },
      { name: 'ois_ts', oisType: 'varchar', oisLength: 26 },
      { name: 'Ejerskab_id', oisType: 'uniqueidentifier' },
      { name: 'EntitetsType', oisType: 'tinyint' },
      { name: 'BbrId', oisType: 'uniqueidentifier' },
      { name: 'Kommune_id', oisType: 'uniqueidentifier' },
      { name: 'ESREjdNr', oisType: 'char', oisLength: 6 },
      { name: 'eRef', oisType: 'uniqueidentifier' },
      { name: 'MereEnd1EjerLej', oisType: 'char', oisLength: 1 },
      { name: 'EjerlejNr', oisType: 'varchar', oisLength: 8 },
      { name: 'ESRArtskode', oisType: 'smallint' },
      { name: 'TinglystAreal', oisType: 'int'},
      { name: 'EJERFORHOLD_KODE', oisType: 'smallint' },
      { name: 'ObjStatus', oisType: 'tinyint' },
      { name: 'OPRET_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'AENDR_TS', oisType: 'varchar', oisLength: 26 },
      { name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40 },
      { name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26 }
    ]
  },
  enhedenhedsadresse: {
    oisTable: 'CO42200T',
    key: ['EnhEnhAdr_id'],
    fields: [{name: 'ois_id', oisType: 'int'},
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      {name: 'EnhEnhAdr_id', oisType: 'uniqueidentifier'},
      {name: 'EnhAdr_id', oisType: 'uniqueidentifier'},
      {name: 'Enhed_id', oisType: 'uniqueidentifier'},
      {name: 'PrimaerAdr', oisType: 'tinyint'},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
    ]
  },
  bygningspunkt: {
    oisTable: 'CO43100T',
    key: ['BygPkt_id'],
    fields: [{name: 'ois_id', oisType: 'int' },
      {name: 'ois_ts', oisType: 'varchar', oisLength: 26},
      {name: 'BygPkt_id', oisType: 'uniqueidentifier'},
      {name: 'Kommune_id', oisType: 'uniqueidentifier'},
      {name: 'PktRevDato', oisType: 'varchar', oisLength: 26},
      {name: 'KoorOest', oisType: 'decimal', oisLength: 9},
      {name: 'KoorNord', oisType: 'decimal', oisLength: 9},
      {name: 'KoorSystem', oisType: 'tinyint'},
      {name: 'TxtRetn', oisType: 'decimal', oisLength: 5},
      {name: 'TxtPlacer', oisType: 'char', oisLength: 1},
      {name: 'DDKNcelle100m', oisType: 'varchar', oisLength: 15},
      {name: 'DDKNcelle1km', oisType: 'varchar', oisLength: 15},
      {name: 'DDKNcelle10km', oisType: 'varchar', oisLength: 15},
      {name: 'OPRET_TS', oisType: 'varchar', oisLength: 26},
      {name: 'AENDR_TS', oisType: 'varchar', oisLength: 26},
      {name: 'Aendr_Funk', oisType: 'varchar', oisLength: 40},
      {name: 'Ophoert_ts', oisType: 'varchar', oisLength: 26},
      {name: 'BygPktKilde', oisType: 'tinyint'},

    ]
  }
};
